# initialization

In [1]:
# Local path to gluten jar.
gluten_target_jar='/opt/gluten/jars/gluten-velox-bundle.jar'

# Select workload. Can be either 'tpch' or 'tpcds'.
workload='tpcds'

# Run with gluten. If False, run Spark.
run_gluten=True

# TPC tables
#tpch_tabledir='/opt/spark/database/tpch_sf10_parquet_zstd'
#tpcds_tabledir='/opt/spark/database/tpch_sf10_parquet_zstd'

tabledir = 's3a://presto-workload/tpcds_sf500_parquet_zstd'

# Database name. if it's set, use the database instead loading table from tabledir
database = ''

# TPC queries
#tpch_query_path='/opt/spark/tpch-queries'
#tpcds_query_path='/opt/spark/tpcds-queries'

tpc_query_path = '/incubator-gluten/tools/gluten-it/common/src/main/resources/tpcds-queries'

# Parallelism
executors_per_node=16

#gluten_tpch_task_per_core=2
#gluten_tpcds_task_per_core=4
#spark_tpch_task_per_core=8
#spark_tpcds_task_per_core=8

task_per_core=2

# Offheap ratio. 0 to disable offheap for Spark.
# onheap:offheap = 1:2
#spark_offheap_ratio=2.0
# onheap:offheap = 1:7
#gluten_offheap_ratio=7.0

offheap_ratio = 7.0

# spark.io.compression.codec
spark_codec='lz4'
# spark.gluten.sql.columnar.shuffle.codec
gluten_codec='lz4'

In [2]:
%env PYSPARK_SUBMIT_ARGS=--driver-java-options -Dio.netty.tryReflectionSetAccessible=true --conf spark.executor.extraJavaOptions=-Dio.netty.tryReflectionSetAccessible=true pyspark-shell

env: PYSPARK_SUBMIT_ARGS=--driver-java-options -Dio.netty.tryReflectionSetAccessible=true --conf spark.executor.extraJavaOptions=-Dio.netty.tryReflectionSetAccessible=true pyspark-shell

In [3]:
%run /opt/spark/work-dir/ipython/native_sql_initialize.ipynb

home: /home/spark
cwd: /opt/spark/work-dir/ipython

,Environment Variable,Value
0,HOSTNAME,ip-10-167-37-206.ec2.internal
1,SHARED_LIBS,/shared-libs
2,JAVA_HOME,/usr/lib/jvm/java-17-openjdk
3,VCPKG_BINARY_SOURCES,"clear;files,/var/cache/vcpkg,readwrite"
4,PWD,/opt/spark/work-dir
5,HOME,/home/spark
6,VCPKG_PATH,/var/cache/vcpkg
7,CCACHE_DIR,/root/.cache/ccache
8,GCC_TOOL,/opt/rh/gcc-toolset-11
9,SPARK_HOME,/opt/spark
10,TERM,xterm-color
11,SPARK_NO_DAEMONIZE,true
12,SHLVL,1
13,PATH,/opt/spark/bin:/bin:/usr/lib/jvm/java-1.8.0-openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/maven/bin
14,_,/usr/local/bin/jupyter
15,LC_CTYPE,C.UTF-8
16,JPY_PARENT_PID,10
17,PYDEVD_USE_FRAME_EVAL,NO
18,CLICOLOR,1
19,FORCE_COLOR,1
20,CLICOLOR_FORCE,1
21,PAGER,cat
22,GIT_PAGER,cat
23,MPLBACKEND,module://matplotlib_inline.backend_inline
24,PYSPARK_SUBMIT_ARGS,--driver-java-options -Dio.netty.tryReflectionSetAccessible=true --conf spark.executor.extraJavaOptions=-Dio.netty.tryReflectionSetAccessible=true pyspark-shell

localhost: ip-10-167-37-206.ec2.internal
ip: 10.167.37.206
Spark version from SPARK_HOME: 3.5.2

# Application Level Configuration

In [4]:
if run_gluten:
    sct=GlutenSparkContext(executors_per_node, task_per_core, gluten_target_jar, offheap_ratio)
else:
    sct=VanillaSparkContext(executors_per_node, task_per_core, gluten_target_jar, offheap_ratio)

In [5]:
if workload.lower()=="tpch":
    bm=TPCHBenchmark(sct, tabledir, 'parquet', tpc_query_path)
else:
    bm=TPCDSBenchmark(sct, tabledir, 'parquet', tpc_query_path)

sct.conf.set('spark.hadoop.fs.s3a.aws.credentials.provider','org.apache.hadoop.fs.s3a.auth.IAMInstanceCredentialsProvider')

if run_gluten:
    sct.conf.set('spark.gluten.sql.columnar.shuffle.codec', gluten_codec)
    sct.conf.set('spark.gluten.sql.columnar.backend.velox.cacheEnabled', False)
    sct.conf.set('spark.gluten.sql.columnar.backend.velox.IOThreads', 48)
    sct.conf.set('spark.gluten.sql.columnar.backend.velox.loadQuantum', 268435456)
    sct.conf.set('spark.gluten.sql.columnar.backend.velox.maxCoalescedBytes', 67108864)
    sct.conf.set('spark.gluten.sql.columnar.backend.velox.maxCoalescedDistanceBytes', 1048576)
    sct.conf.set('spark.gluten.sql.columnar.backend.velox.memCacheSize', 134217728)
    sct.conf.set('spark.gluten.sql.columnar.backend.velox.prefetchRowGroups', 1)
    sct.conf.set('spark.gluten.sql.columnar.backend.velox.SplitPreloadPerDriver', 16)
    sct.conf.set('spark.gluten.sql.columnar.backend.velox.ssdCacheSize', 0)
    sct.conf.set('spark.locality.wait', 0)

else:
    sct.conf.set('spark.io.compression.codec', spark_codec)
    
bm.initialize()

            executors per node: 16
            parallelism: 32
            executor memory: 1024m
            offheap memory: 7168m

spark.serializer:  org.apache.spark.serializer.KryoSerializer
master:  spark://ip-10-167-37-206.ec2.internal:7077

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/08/15 07:03:58 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
W20250815 07:04:00.143832 111635 MemoryArbitrator.cpp:84] Query memory capacity[12.75GB] is set for NOOP arbitrator which has no capacity enforcement
/opt/spark/python/pyspark/sql/context.py:113: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  warnings.warn(

appid:  app-20250815070400-0006
SparkConf:

,key,value
0,spark.driver.host,ip-10-167-37-206.ec2.internal
1,spark.gluten.sql.columnar.backend.velox.cacheEnabled,False
2,spark.driver.extraClassPath,/opt/gluten/jars/gluten-velox-bundle.jar
3,spark.executor.extraClassPath,/opt/gluten/jars/gluten-velox-bundle.jar
4,spark.executor.instances,16
5,spark.gluten.sql.columnar.shuffle.codec,lz4
6,spark.executor.extraJavaOptions,-Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false -Dio.netty.tryReflectionSetAccessible=true
7,spark.cleaner.periodicGC.interval,10s
8,spark.serializer,org.apache.spark.serializer.KryoSerializer
9,spark.master,spark://ip-10-167-37-206.ec2.internal:7077
10,spark.app.submitTime,1755241438473
11,spark.default.parallelism,32
12,spark.locality.wait,0
13,spark.gluten.sql.columnar.backend.velox.SplitPreloadPerDriver,16
14,spark.driver.memory,20480m
15,spark.executorEnv.PYTHONPATH,/opt/sparkpython:/opt/spark/python/lib/py4j-0.10.9.7-src.zip
16,spark.app.startTime,1755241438601
17,spark.hadoop.fs.s3a.aws.credentials.provider,org.apache.hadoop.fs.s3a.auth.IAMInstanceCredentialsProvider
18,spark.executor.memoryOverhead,17408m
19,spark.gluten.memoryOverhead.size.in.bytes,18253611008
20,spark.gluten.sql.columnar.backend.velox.IOThreads,48
21,spark.executor.id,driver
22,spark.sql.extensions,org.apache.gluten.extension.GlutenSessionExtensions
23,spark.app.id,app-20250815070400-0006
24,spark.gluten.memory.conservative.task.offHeap.size.in.bytes,3758096384
25,spark.sql.catalogImplementation,hive
26,spark.executorEnv.LD_PRELOAD,/usr/lib64/libjemalloc.so.2
27,spark.gluten.sql.columnar.coalesce.batches,true
28,spark.gluten.memory.overAcquiredMemoryRatio,0
29,spark.driver.maxResultSize,4g
30,spark.gluten.sql.columnar.backend.velox.maxCoalescedDistanceBytes,1048576
31,spark.gluten.sql.columnar.joinOptimizationLevel,18
32,spark.gluten.sql.columnar.backend.velox.loadQuantum,268435456
33,spark.gluten.sql.columnar.backend.velox.prefetchRowGroups,1
34,spark.sql.optimizer.runtime.bloomFilter.applicationSideScanSizeThreshold,0
35,spark.plugins,org.apache.gluten.GlutenPlugin
36,spark.kryoserializer.buffer.max,512m
37,spark.sql.files.maxPartitionBytes,4g
38,spark.sql.adaptive.enabled,True
39,spark.memory.offHeap.size,7168m
40,spark.sql.shuffle.partitions,32
41,spark.gluten.memory.offHeap.size.in.bytes,7516192768
42,spark.app.name,gluten_tpcds_spark352
43,spark.gluten.sql.columnar.physicalJoinOptimizeEnable,true
44,spark.gluten.sql.columnar.physicalJoinOptimizationLevel,18
45,spark.gluten.sql.columnar.forceShuffledHashJoin,True
46,spark.sql.autoBroadcastJoinThreshold,10m
47,spark.serializer.objectStreamReset,100
48,spark.submit.deployMode,client
49,spark.gluten.sql.columnar.backend.velox.memCacheSize,134217728
50,spark.memory.offHeap.enabled,True
51,spark.gluten.sql.columnar.logicalJoinOptimizeEnable,true
52,spark.gluten.memory.task.offHeap.size.in.bytes,7516192768
53,spark.gluten.sql.columnar.backend.velox.maxCoalescedBytes,67108864
54,spark.sql.optimizer.dynamicPartitionPruning.enabled,True
55,spark.shuffle.manager,org.apache.spark.shuffle.sort.ColumnarShuffleManager
56,spark.gluten.sql.columnar.backend.lib,velox
57,spark.driver.extraJavaOptions,-Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false -Dio.netty.tryReflectionSetAccessible=true
58,spark.gluten.sql.columnar.maxBatchSize,4096
59,spark.gluten.numTaskSlotsPerExecutor,1
60,spark.gluten.sql.columnar.backend.velox.ssdCacheSize,0
61,spark.executor.memory,1024m
62,spark.rdd.compress,True
63,spark.sql.broadcastTimeout,4800
64,spark.task.cpus,1
65,spark.sql.adaptive.customCostEvaluatorClass,org.apache.spark.sql.execution.adaptive.GlutenCostEvaluator
66,spark.submit.pyFiles,
67,spark.kryo.unsafe,False
68,spark.executor.cores,1
69,spark.ui.showConsoleProgress,true
70,spark.sql.optimizer.runtime.bloomFilter.enabled,true
71,spark.driver.port,35295

start run:  app-20250815070400-0006
http://10.167.37.206:18080/history/app-20250815070400-0006/jobs/

In [6]:
bm.test_tpc.load_all_tables_as_tempview()

Loading all tables: ['call_center', 'catalog_page', 'catalog_returns', 'catalog_sales', 'customer', 'customer_address', 'customer_demographics', 'date_dim', 'household_demographics', 'income_band', 'inventory', 'item', 'promotion', 'reason', 'ship_mode', 'store', 'store_returns', 'store_sales', 'time_dim', 'warehouse', 'web_page', 'web_returns', 'web_sales', 'web_site']

In [7]:
sct.spark.sql('''
select count(*) h8_30_to_9
 from store_sales, household_demographics , time_dim, store
 where ss_sold_time_sk = time_dim.t_time_sk   
     and ss_hdemo_sk = household_demographics.hd_demo_sk 
     and ss_store_sk = s_store_sk
     and time_dim.t_hour = 8
     and time_dim.t_minute >= 30
     and ((household_demographics.hd_dep_count = 3 and household_demographics.hd_vehicle_count<=3+2) or
          (household_demographics.hd_dep_count = 0 and household_demographics.hd_vehicle_count<=0+2) or
          (household_demographics.hd_dep_count = 1 and household_demographics.hd_vehicle_count<=1+2)) 
     and store.s_store_name = 'ese'
''').collect()

[Row(h8_30_to_9=891135)]

In [8]:
sct.sc.stop()

# Run Workload

In [ ]:
if database!="":
    load_table=False
    bm.sct.spark.sql("use " + database)
else:
    load_table=True
    if tabledir=="":
        raise "Either database or tabledir should be set"

In [ ]:
!echo "" > /opt/spark/work-dir/telegraf.out

In [ ]:
bm.test_tpc.power_run(explain=False, print_result=False, load_table=load_table, action=lambda df: df.collect())

In [ ]:
bm.test_tpc.print_result()

In [ ]:
#collect_worker=false, jenkins host will do the collection fro workers
bm.collect_profile(False)